

Vagrant.configure(2) do |config|
  # You can download this from the ubuntu site, then add the 
  # box to vagrant.
  # $ vagrant box add --name ubuntu https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-amd64-vagrant-disk1.box
  config.vm.box = "ubuntu"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
     # Customize the amount of memory on the VM:
     vb.memory = "2048"
  end
end
